version: "3"
services:
  cron-and-queue:
    image: freen/wires-and-rails-workflow-processing:latest
    volumes:
      - .:/app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
    depends_on:
      - redis
    ports:
      - "9181:9181" # rq-dashboard
    env_file: .env
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
