version: "3"
services:
  cron-and-queue:
    image: freen/wires-and-rails-workflow-processing:latest
    volumes:
      - .:/app
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 500M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    depends_on:
      - redis
    deploy:
      placement:
        constraints: [node.role == manager]
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  rq-dashboard:
    image: robbieclarken/lightweight-rq-dashboard
    command: rq-dashboard -H redis
    depends_on:
      - redis
    ports:
      - "9181:9181"
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    networks:
      - webnet
networks:
  webnet:
