version: "3"
services:
  cron:
    image: freen/wires-and-rails-workflow-processing:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 500M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    deploy:
      placement:
        constraints: [node.role == manager]
  rq-worker:
    build:
      context: ./rq-worker
      dockerfile: ./rq-worker/Dockerfile
    networks:
      - webnet
    deploy:
      placement:
        constraints: [node.role == manager]
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
